apiVersion: v1
kind: Service
metadata:
    name: hello-service
    labels:
        app: hello
spec:
    type: LoadBalancer
    selector:
        app: hello
        component: backend
    ports:
        - port: 3000
          name: http
          targetPort: 3000
