name: "Release Tags Test"

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+.*'

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - run: echo "Test"
